### ISSUE TITLE
Doesn't work if the target url redirects.

### ISSUE THREAD

**Issue by ayushbhetwal** [un9nplayer/AutoRecon-XSS#1]
If the target redirects to login panel or somewhere else. it throws an error 
Error: The target URL did not return status code 200 OK.

Make an option not to follow redirection.

**Comment by un9nplayer** [comment]
Thanks @ayushbhetwal i will look into it and and fix it asap.

**Comment by un9nplayer** [comment]
Thanks @ayushbhetwal I will look into it and fix it asap.

**Comment by un9nplayer** [comment]
Hi @ayushbhetwal it seems to okay to me.
because the testing must be done on the 200 code not on 301,302 and if you are still want to test it. You can change the script code on your behalf.
closing this issue as solved.

thanks
